### ISSUE TITLE
Clickable images from external URL

### ISSUE THREAD

**Issue by nhlpl** [NodeBB/nodebb-plugin-iframely#17]
https://community.nodebb.org/topic/8312/zenith-v1-preview

Click on image created from URL (`http://convoe.com`) to open `http://convoe.com/uploads/system/site-logo.png` image in a new window.

`<a href="http://convoe.com/uploads/system/site-logo.png" target="_blank"><img src="http://convoe.com/uploads/system/site-logo.png" class="img-responsive"></a>`

Please remove a link as it sometimes redirect to a random page and not showing an image. I mean when posting some other URLs.

**Comment by iparamonau** [comment]
I don't see that link is in Iframely templates (and not in the page's source). If anything, we would link it to the canonical URL, not to the image src. 

@julianlam @psychobunny can you guys take a look if this is something that you're adding?

**Comment by julianlam** [comment]
Try v0.6.9 of iframely plugin and see if the same symptoms continue to occur.

**Comment by iparamonau** [comment]
Assuming this is now resolved
