### ISSUE TITLE
Hash parts of URLs get removed

### ISSUE THREAD

**Issue by ghost** [NodeBB/nodebb-plugin-iframely#20]
E.g. http://semver.org/#introduction links to http://semver.org/
Hashes should be preserved even for more complex URL manipulations like
https://docs.nodebb.org/en/latest/themes/templates.html#how-it-works
to
http://nodebb-francais.readthedocs.org/projects/nodebb/en/latest/themes/templates.html#how-it-works

**Comment by nleush** [comment]
I believe this was fixed in 49bb848084cac7638c5bae2a1fb90a20f7879831
