### ISSUE TITLE
Composer preview should not include scripts, media, or iframes

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/nodebb-plugin-iframely#25]
A certain user of our forum has complained that pasting a link and then typing the rest of the post causes a request to the server (for example, Twitter or YouTube) on every keypress. It would be beneficial to only include static images and text in the composer preview (parseRaw), or perhaps a [placeholder div containing an icon representing embedding](http://i.stack.imgur.com/3vQ6L.png).

**Comment by yamikuronue** [comment]
That or cache the result so only one request is made. The bug is that it's sending a bajillion requests.

**Comment by BenLubar** [comment]
@yamikuronue the request is made by a third party script (in this case, Twitter's embed script), so it'd have to be a modification of how the composer updates its preview.

**Comment by yamikuronue** [comment]
Sure, but the composer could, say, render an image of the first request and show that. 

In general when filing bug reports I like to avoid mandating a particular solution and let the devs figure out the best way to resolve it

**Comment by julianlam** [comment]
Just an idle thought, but one wonders if you could selectively change text nodes based on a diff of the old and new raw input...

**Comment by nleush** [comment]
Well it appears I committed everything right away into the master… Please take a quick look at the referenced changes before I publish a new version to NPM. Basically, the preview will show either the first time it loads, or when user clicks additional “click to preview” in post’s preview.

**Comment by iparamonau** [comment]
This is now resolved. Preview is shown with first request, and if user continues typing, the embed preview is folded, but user can expand it to preview.
