### ISSUE TITLE
remove old iframely embeds

### ISSUE THREAD

**Issue by geransmith** [NodeBB/nodebb-plugin-iframely#26]
In an effort to cut down on the number of hits on the Iframely API, it would be great if posts older than a specified age removed the embed. This might help cut down on long threads with lots of embeds triggering 20+ API calls.

**Comment by julianlam** [comment]
Hm, I'd recommend this be an admin setting, since I can see the case being made that even old posts should have embeds expanded...

**Comment by iparamonau** [comment]
Do not see this as necessary - the older posts will fade away naturally anyway. Besides, it will be tricky to implement. For example, there are pinned posts.... 

We now have a config option for cache TTL. That should address the number of hits concern.
