### ISSUE TITLE
change cache length in the ACP

### ISSUE THREAD

**Issue by geransmith** [NodeBB/nodebb-plugin-iframely#28]
As is, the plugin is configured to cache iframely data for one day. This leads to a huge amount of API hits. It is possible to manually change the cache length via this line (https://github.com/NodeBB/nodebb-plugin-iframely/blob/master/library.js#L21-L23)

I'd suggest adding a configurable option on the ACP to change how long iframely caches information.

I found that setting it to seven days doesn't consume too much memory and bumped me down from ~20K hits to ~10K, which is huge.

**Comment by iparamonau** [comment]
This config option is now available in v0.7.0
