### ISSUE TITLE
[plugin/iframely] Could not parse embed! TypeError: This library (validator.js) validates strings only

### ISSUE THREAD

**Issue by BenLubar** [NodeBB/nodebb-plugin-iframely#31]
```
24/7 14:51:42 [3641] - error: [4568/3641] [plugin/iframely] Could not parse embed! TypeError: This library (validator.js) validates strings only
24/7 14:51:42 [3641] - error: [4568/3641]  Error: Callback was already called.
    at /usr/src/app/node_modules/async/dist/async.js:903:32
    at /usr/src/app/node_modules/async/dist/async.js:1071:13
    at Immediate.<anonymous> (/usr/src/app/node_modules/nodebb-plugin-iframely/library.js:310:5)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

https://github.com/NodeBB/nodebb-plugin-iframely/blob/72bd373dc4dcc74ec9a6783d50d9cb2cae134d37/library.js#L310

Don't have time to look into it further right now, but I'll look later today if I have time.

**Comment by nleush** [comment]
I think problem was with code line: https://github.com/NodeBB/nodebb-plugin-iframely/blob/master/library.js#L255

`context.embedHtmlEscaped = validator.escape(embedHtml);`

when embedHtml is null or undefined. I've made some changes to prevent this 4e02831e42e9a8a4b6e20f1c4015510e7283cfa4
