### ISSUE TITLE
Processing error: HPE_INVALID_METHOD

### ISSUE THREAD

**Issue by NormandoHall** [NodeBB/nodebb-plugin-iframely#38]
Hello

I have iFramely running in localhost and nodebb-plugin.iframely also. After upgrade nodejs to 10.x I get these error messages on all links in nodebb forum.

This is one example, and there is no render for the link, only as legacy `<a href`.

`[plugin/iframely] iframely responded with error: {"error":{"source":"iframely","code":417,"message":"Processing error: HPE_INVALID_METHOD"}}. Url: http://www.tortasycocteles.com/shop/index.php?id_category=50&amp;controller=category. Api call: https://iframely.vapeandoargentina.com.ar/iframely?url=http%3A%2F%2Fwww.tortasycocteles.com%2Fshop%2Findex.php%3Fid_category%3D50%26amp%3Bcontroller%3Dcategory&group=true
`

Can I do something to fix this issue? Before nodejs upgrade runs ok.

NodeJS v10.4.1
NodeBB: v1.10.1
nodebb-plugin-iframely: 0.7.8
iframely: 1.2.5

Regards,
Normando Hall

**Comment by RikoDEV** [comment]
I have the same problem.

NodeBB: 1.10.1
Iframely: 1.2.6
nodebb-plugin-iframely: 0.7.8
Node.js: 10.8.0

**Comment by NormandoHall** [comment]
Very very strange. Running iframely with "node server" runs like a charm.

https://github.com/itteco/iframely/issues/197

**Comment by iparamonau** [comment]
Please update Iframely to v1.2.7 to resolve. Open any follow-up issues in our main repo.
