### ISSUE TITLE
Cloud vs. Self-hosted

### ISSUE THREAD

**Issue by FreeWoRLD83** [NodeBB/nodebb-plugin-iframely#41]
I am getting significant difference in the output of the iFramely API VS. the self hosted versions as shown in screens below. 
Is the difference in look what I am supposed to get or am I missing something in the config of the plugin - please let me know your thoughts. 

Thanks!

**Cloud Version;**
![Screen Shot 2019-09-02 at 23 19 19](https://user-images.githubusercontent.com/6927136/64142007-3d80ec00-cdd8-11e9-92c8-6c4e179cb71d.png)

**Self Hosted version;**
![Screen Shot 2019-09-02 at 23 19 09](https://user-images.githubusercontent.com/6927136/64142009-407bdc80-cdd8-11e9-8e2d-2986f1d729de.png)

**Comment by iparamonau** [comment]
Hey @freestylemaster, please take a look at what's not included in the self-hosted version as compared to the cloud: 
https://github.com/itteco/iframely#not-included-as-compared-to-cloud-api

Your screenshot shows the summary cards for URL previews. Those are handled in the cloud for cloud version. URL previews and any HTML renders in general are not included in the self-hosted version, just the raw URL data and semantics. This very NodeBB plugin adds some renders for that data, hence your second screenshot.

**Comment by FreeWoRLD83** [comment]
Thank you
