### ISSUE TITLE
is it compatible with latest master? 

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-plugin-iframely#44]
we could not make it work with 1.13.4-5... there is no errors in the log but none of the links are transformed... 

should we wait for stable version ?

**Comment by julianlam** [comment]
Yes, there is no reason this plugin should not work with the latest version of NodeBB... have you signed up for an API key and put it into the plugin settings?

**Comment by barisusakli** [comment]
It is installed on our community https://community.nodebb.org/topic/10963/test-iframely

**Comment by julianlam** [comment]
I am also testing it on my development instance with no issues.

**Comment by AliCihan** [comment]
Thanks... we are self-hosting... 

We have just resolved the issue today with this suggestion:
https://github.com/itteco/iframely/issues/275
