### ISSUE TITLE
Can we add forum's domain name to API calls?

### ISSUE THREAD

**Issue by iparamonau** [NodeBB/nodebb-plugin-iframely#6]
We would love to see it as `&origin=domain.name` query string param.

**Comment by iparamonau** [comment]
or better yet `&origin=nodebb-domain.name`, with nodebb hardcoded prefix. This way we would be able to attribute API keys to this plugin

**Comment by julianlam** [comment]
@iparamonau Sure, that can be done, though we'd be retrieving the value from the server configuration, so you may get a lot of `&origin=localhost:4567` as users may be testing/installing it on their local machines, or forget to change the base_url. :laughing:

**Comment by iparamonau** [comment]
Yeah, it's fine. The side reason for the origin is that if we publish plugin with an open endpoint fallback, then there better be a way for us to block some domains if need be.

**Comment by julianlam** [comment]
Assuming you'd block origins without `?=origin=nodebb-` prefix?

**Comment by iparamonau** [comment]
Our mechanisms can go after specific origins like `nodebb-iframely.com` that are linking to open endpoints.
